### ISSUE TITLE
Just a heads-up that this repository is public

### ISSUE THREAD

**Issue by JPedroRSilva** [gympass/cdn-origin-controller#74]
I'm currently in an interview process with you guys, and I'm checking out a few repos with guidelines for the interview and noticed that this repo is public, so I'm assuming that either this is supposed to be open-sourced or private. In case this is supposed to be like this, then just let me know, and I will delete this issue.  Ps: Pinky swear that I did not look at the code 🤣

**Comment by LCaparelli** [comment]
Thanks @senhorfrederico, this is meant to be open-source 😁
